env:
- SECRET_A=alpha

script:
- echo Safety -- alpha bravo charlie delta
- echo $SECRET_A $(echo $SECRET_A | cut -c1-2) - Plain ENV in .yml
- echo $SECRET_B $(echo $SECRET_B | cut -c1-2) - ENV in Travis shown in log
- echo $SECRET_C $(echo $SECRET_C | cut -c1-2) - ENV in Travis hidden from log
- echo $SECRET_D $(echo $SECRET_D | cut -c1-2) - Encrypted ENV in .yml
